### ISSUE TITLE
Update README.md to indicate the use of Python 2.7 

### ISSUE THREAD

**Issue by wannabeOG** [AKSW/NSpM#14]
Since the support for Python2 is now being rescinded, it would be great if the README.md could indicate that code had been written in Python2 so any future developers could set up the appropriate development environment.

**Comment by wannabeOG** [comment]
I can also rewrite the python codebase in Python3 syntax if you guys think it to be necessary

**Comment by mommi84** [comment]
Codebase upgraded to Python 3.7+ in NSpM v1.0.0.
