### ISSUE TITLE
Possible fault in version check implemented in nmt (linked to tensorflow's implementation)

### ISSUE THREAD

**Issue by wannabeOG** [AKSW/NSpM#15]
The version check in nmt/utils/misc_utils.py has a snippet of code for checking the version of TF installed on the local machine 

```Python
def check_tensorflow_version():
  if tf.__version__ < "1.2.1":
    raise EnvironmentError("Tensorflow version must >= 1.2.1")
```

I have tested out the code using both the current version of TF as well as TF-nightly as the authors want you to do (mentioned on their README.md). The current version is 1.12 and it is obvious the check is failing because it's comparing the versions numerically.

I have created an issue on the main project of nmt as well, but since this would affect the working of this project as well, I am also opening an issue here.

**Comment by nabito** [comment]
The following command solved the problem.

git submodule update --recursive --remote

Ref: [https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules](url)
