### ISSUE TITLE
fault in tensorflow version check

### ISSUE THREAD

**Issue by ssubbstring** [AKSW/NSpM#16]
wrong output of tensorflow version check in NSpM/nmt/nmt/utils/misc_utils.py
EnvironmentError: Tensorflow version must >= 1.2.1 

changes to be made
from
  ```
if tf.__version__ < “1.2.1”:
    raise EnvironmentError("Tensorflow version must >= 1.2.1”)
```
to 
```  
if tf.__version__ < "1.02.1":
    raise EnvironmentError("Tensorflow version must >= 1.02.1")
```

**Comment by wannabeOG** [comment]
A duplicate issue, it has already been opened, the changes need to be incorporated in nmt implemented by TF, which has been linked to in the repository 
Check issue #15
