### ISSUE TITLE
ZeroDivisionError while training

### ISSUE THREAD

**Issue by pymit** [AKSW/NSpM#18]
File "nmt/model_helper.py", line 444, in compute_perplexity
    perplexity = utils.safe_exp(total_loss / total_predict_count)
ZeroDivisionError: integer division or modulo by zero

**Comment by theodore3131** [comment]
Hi, I solved it by modifying the code as below
```python
if total_predict_count > 0:
    perplexity = utils.safe_exp(total_loss / total_predict_count)
  else:
    perplexity = 0
```
I have done the training process and the model for Inference performs really well.
But  the thing is, by doing so, we will get
```
eval test: perplexity 0.00
```
and the output_test will be empty
By the way, 
there is also a ZeroDivisionError in bleu.py
and I changed likewise.

**Comment by theodore3131** [comment]
Fixed, pull request has been made
