### ISSUE TITLE
Fixes in README.md

### ISSUE THREAD

**Issue by panchbhai1969** [AKSW/NSpM#20]
It may seem trivial, but README.md files are the first point of information that a parson refers to when trying to understand a project, The repository's README.md is good, but i have found some error that need attention.  

`NUMLINES= $(echo awk '{ print $1}' | cat data/monument_300/data_300.sparql |  wc -l)`
There shouldn't be any space after =, the line should be : 
`NUMLINES=$(echo awk '{ print $1}' | cat data/monument_300/data_300.sparql |  wc -l)`

Other README.md related issues and suggestions brought up by users are #12 #14 #17

**Comment by thisisshub** [comment]
@panchbhai1969 
I believe #14 still isn't solved or mentioned in the current [README.md](https://github.com/AKSW/NSpM/blob/master/README.md). Should I make a PR to asses the required changes?
