### ISSUE TITLE
ZeroDivisionError when run command train

### ISSUE THREAD

**Issue by HuuDung** [AKSW/NSpM#27]
When I run the command **sh train.sh data/monument_300 120000** the following error appears ZeroDivisionError: integer division or modulo by zero
![Screenshot from 2019-11-16 19-05-12](https://user-images.githubusercontent.com/32788273/68992884-0af97200-08a4-11ea-9a15-d6a47617fbf5.png)

**Comment by panchbhai1969** [comment]
Hi @HuuDung, check the way data is being split in split_in_train_dev_test.py file, that will tell you why this error is happening.

**Comment by HuuDung** [comment]
Hi @panchbhai1969 , thank you for help me.That error has been resolved but now there is another error 
![Screenshot from 2019-11-16 20-37-17](https://user-images.githubusercontent.com/32788273/68994047-e952b780-08b0-11ea-9a73-18e698743905.png)
