### ISSUE TITLE
Issues while running pipeline 1

### ISSUE THREAD

**Issue by KShivendu** [AKSW/NSpM#30]
I tried running the pipelines but because of some python version related issues I was getting errors in pipeline 1.

The solution which worked was using 
`from urllib.request import urlopen` and then `urlopen(<url>)`
instead of  `import urllib`and then using `urllib.request.urlopen(<url>)`
Make sure to use `python3.7` to run the pipelines as @panchbhai1969 's code uses it.

It works becuase 
`The urllib and urllib2 modules from Python 2.x have been combined into the urllib module in Python 3` as mentioned [here](https://stackoverflow.com/questions/2792650/import-error-no-module-name-urllib2)

Also, while setting up the project I realised it will be better to have a `requirements.txt` file.
I would like to do it too as my initial contribution.

**Comment by panchbhai1969** [comment]
Hi @KShivendu ,

Okay, I understand the issue. Adding a `requirement.txt` will be a very useful add-on in making the repository more user friendly. Please raise this issue in: [https://github.com/dbpedia/neural-qa](https://github.com/dbpedia/neural-qa ) instead, as the code you are referring to is present in that repository which is forked from this one.

**Comment by KShivendu** [comment]
Sure, I will do that.
