### ISSUE TITLE
Error in path in ask.sh?

### ISSUE THREAD

**Issue by picorana** [AKSW/NSpM#5]
Hey, I don't know if I am just misunderstanding the instructions, but the project kept giving me ValueError:"Can't load save_path when it is None." if I tried to precisely follow the instructions in the readme.

I believe it would work correctly with your readme instructions if you would change this part of ask.sh:
`python -m nmt.nmt --vocab_prefix=../$1/vocab --model_dir=../$1_model --inference_input_file=./to_ask.txt --inference_output_file=./output.txt --out_dir=../$1_model --src=en --tgt=sparql | tail -n4`

to this:
`python -m nmt.nmt  --vocab_prefix=../$1/vocab --model_dir=../$1  --inference_input_file=./to_ask.txt  --inference_output_file=./output.txt --out_dir=../$1 --src=en --tgt=sparql | tail -n4`
(that $1_model makes it repeat the word weirdly in the folder names)

Please, feel free to correct me if I am wrong, and thank you for your awesome paper.

**Comment by mommi84** [comment]
Hi @picorana and thanks a lot! We are going to fix this with the next commit.
